#SIM = icarus
#TOPLEVEL_LANG = verilog
#VERILOG_SOURCES = $(PWD)/dff.v
#TOPLEVEL = dff
#MODULE = test_dff

#include $(shell cocotb-config --makefiles)/Makefile.sim

#SIM = icarus
#TOPLEVEL_LANG = verilog

#VERILOG_SOURCES = $(PWD)/counter.v    # 파일명 변경
#TOPLEVEL = counter                    # 모듈명 변경
#MODULE = test_counter                 # 파이썬 파일명 변경

#include $(shell cocotb-config --makefiles)/Makefile.sim

SIM = icarus
TOPLEVEL_LANG = verilog

VERILOG_SOURCES = $(PWD)/vending.v
TOPLEVEL = vending
COCOTB_TEST_MODULES = test_vending

include $(shell cocotb-config --makefiles)/Makefile.sim